// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	person "github.com/jonathanleahy/prroxy/rest-v2/internal/person"
	mock "github.com/stretchr/testify/mock"
)

// PersonService is an autogenerated mock type for the PersonService type
type PersonService struct {
	mock.Mock
}

// FindPeople provides a mock function with given fields: ctx, surname, dob
func (_m *PersonService) FindPeople(ctx context.Context, surname string, dob string) ([]person.Person, error) {
	ret := _m.Called(ctx, surname, dob)

	if len(ret) == 0 {
		panic("no return value specified for FindPeople")
	}

	var r0 []person.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]person.Person, error)); ok {
		return rf(ctx, surname, dob)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []person.Person); ok {
		r0 = rf(ctx, surname, dob)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]person.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, surname, dob)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPerson provides a mock function with given fields: ctx, surname, dob
func (_m *PersonService) FindPerson(ctx context.Context, surname string, dob string) (*person.Person, error) {
	ret := _m.Called(ctx, surname, dob)

	if len(ret) == 0 {
		panic("no return value specified for FindPerson")
	}

	var r0 *person.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*person.Person, error)); ok {
		return rf(ctx, surname, dob)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *person.Person); ok {
		r0 = rf(ctx, surname, dob)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*person.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, surname, dob)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonService creates a new instance of PersonService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonService {
	mock := &PersonService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
