// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/jonathanleahy/prroxy/rest-v2/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *UserService) GetUser(ctx context.Context, userID int) (*user.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*user.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *user.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserReport provides a mock function with given fields: ctx, userID, req
func (_m *UserService) GetUserReport(ctx context.Context, userID int, req user.ReportRequest) (*user.UserReport, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserReport")
	}

	var r0 *user.UserReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, user.ReportRequest) (*user.UserReport, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, user.ReportRequest) *user.UserReport); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, user.ReportRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSummary provides a mock function with given fields: ctx, userID
func (_m *UserService) GetUserSummary(ctx context.Context, userID int) (*user.UserSummary, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSummary")
	}

	var r0 *user.UserSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*user.UserSummary, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *user.UserSummary); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
